version: "3.8"

services:
  client:
    build:
      context: ..
      dockerfile: ./docker/client.dockerfile
    image: relmgren/client
    restart: "no"
    ports:
      - 8080:80

  server:
    build:
      context: ..
      dockerfile: ./docker/server.dockerfile
    image: relmgren/server
    restart: "no"
    ports:
      - 5001:3001